### ISSUE TITLE
Why is it wrong?     java.io.FileNotFoundException: env

### ISSUE THREAD

**Issue by LoveSeriously** [meefik/linuxdeploy#1128]
W/System.err: java.io.FileNotFoundException: env
W/System.err:     at android.content.res.AssetManager.nativeOpenAsset(Native Method)
W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:748)
W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:725)
W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.extractFile(EnvUtils.java:53)
W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.extractDir(EnvUtils.java:87)
W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.updateEnv(EnvUtils.java:318)
W/System.err:     at ru.meefik.linuxdeploy.UpdateEnvTask.doInBackground(UpdateEnvTask.java:32)
W/System.err:     at ru.meefik.linuxdeploy.UpdateEnvTask.doInBackground(UpdateEnvTask.java:10)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by ElXreno** [comment]
If you build this application from source code, do not forget about git submodules. You need clone submodules too.
