### ISSUE TITLE
npm start bind port 8360 was wrong

### ISSUE THREAD

**Issue by WhiteSnowGirl** [meefik/linuxdeploy#1341]
```
[root@localhost server_home_note]# npm start

> server_home_note@1.0.0 start
> node development.js

[2022-12-13T16:46:54.707] [31687] [INFO] - Server running at http://127.0.0.1:8360
[2022-12-13T16:46:54.716] [31687] [INFO] - ThinkJS version: 3.2.14
[2022-12-13T16:46:54.717] [31687] [INFO] - Environment: development
[2022-12-13T16:46:54.718] [31687] [INFO] - Workers: 1
[2022-12-13T16:46:55.501] [31694] [ERROR] - uncaughtException, times: 1, pid: 31694
[2022-12-13T16:46:55.503] [31694] [ERROR] - Error: bind EACCES null:8360
    at listenOnPrimaryHandle (node:net:1531:18)
    at rr (node:internal/cluster/child:159:12)
    at Worker.<anonymous> (node:internal/cluster/child:109:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:525:35)
    at process.emit (/www/wwwroot/homenote/server_home_note/node_modules/source-map-support/source-map-support.js:439:21)
    at emit (node:internal/child_process:946:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'bind',
  address: null,
  port: 8360
}
[2022-12-13T16:46:55.504] [31694] [ERROR] - Error: bind EACCES null:8360
    at listenOnPrimaryHandle (node:net:1531:18)
    at rr (node:internal/cluster/child:159:12)
    at Worker.<anonymous> (node:internal/cluster/child:109:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:525:35)
    at process.emit (/www/wwwroot/homenote/server_home_note/node_modules/source-map-support/source-map-support.js:439:21)
    at emit (node:internal/child_process:946:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'bind',
  address: null,
  port: 8360
}
```
I want to run npm start in linux deploy ; i dont understant ,what's wrong

**Comment by WhiteSnowGirl** [comment]
`[root@localhost ~]# systemctl start firewalld.service
Running in chroot, ignoring request.
[root@localhost ~]# `

**Comment by WhiteSnowGirl** [comment]
i think meybe my project problem,i don't know
