### ISSUE TITLE
Stealth Mode revert

### ISSUE THREAD

**Issue by TemhAAhmeT** [meefik/linuxdeploy#621]
Hi,
Everything fine but when activated stealth mode naturally linux deploy icon from launcher gone. So how can i launch linux deploy or restore that missing icon?

**Comment by meefik** [comment]
From Android terminal:
```
am start -n ru.meefik.linuxdeploy/.MainActivity
```
and unckeck this option.

**Comment by TemhAAhmeT** [comment]
Thanks for fast reply :D 
I was trying to chnage it in data folder settings_conf.xml.

**Comment by bots-developer** [comment]
Thank you bruh was really helpful

**Comment by aletheus** [comment]
This is my output from running the above command:

`Starting: Intent { cmp=ru.meefik.linuxdeploy/.MainActivity }
java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=ru.meefik.linu
deploy/.MainActivity } from null (pid=14408, uid=10177) not exported from uid 10161
        at android.os.Parcel.readException(Parcel.java:1425)
        at android.os.Parcel.readException(Parcel.java:1379)
        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:1987)
        at com.android.commands.am.Am.runStart(Am.java:463)
        at com.android.commands.am.Am.run(Am.java:108)
        at com.android.commands.am.Am.main(Am.java:81)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:280)
        at dalvik.system.NativeStart.main(Native Method)`

**Comment by michager** [comment]
in Android 4.4.4 with latest linux deploy the command is slightly different

from inside chroot: unchroot su -c "am start -n ru.meefik.linuxdeploy/.activity.MainActivity"

open adb shell
su for root
execute: adb shell am start -n ru.meefik.linuxdeploy/.activity.MainActivity
