### ISSUE TITLE
Unable to run Native commands (Latest Build) - java.io.IOException: Error running exec(). Command: [su] / [env]..

### ISSUE THREAD

**Issue by rkkoszewski** [meefik/linuxdeploy#627]
I don't know if this is a bug in the latest source or if I'm doing something wrong. 

I cannot start any system because Linux Deploy fails in setting some kind of "System Environment". 

Here is a complete Log of the starup of Linux Deploy.

```
10-27 13:00:47.246 12204-12204/? I/art: Late-enabling -Xcheck:jni
10-27 13:00:47.365 12204-12204/ru.meefik.linuxdeploy W/System: ClassLoader referenced unknown path: /data/app/ru.meefik.linuxdeploy-2/lib/arm
10-27 13:00:47.818 12204-12204/ru.meefik.linuxdeploy W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
10-27 13:00:48.486 12204-12256/ru.meefik.linuxdeploy D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
10-27 13:00:49.552 12204-12204/ru.meefik.linuxdeploy I/Choreographer: Skipped 62 frames!  The application may be doing too much work on its main thread.
10-27 13:00:49.701 12204-12256/ru.meefik.linuxdeploy I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
10-27 13:00:49.834 12204-12256/ru.meefik.linuxdeploy I/OpenGLRenderer: Initialized EGL, version 1.4
10-27 13:00:50.366 12204-12212/ru.meefik.linuxdeploy W/art: Suspending all threads took: 12.242ms
10-27 13:00:50.404 12204-12335/ru.meefik.linuxdeploy W/System.err: java.io.IOException: Error running exec(). Command: [sh] Working Directory: /data/user/0/ru.meefik.linuxdeploy/env Environment: [ANDROID_ROOT=/system, LD_PRELOAD=libsigchain.so, ANDROID_BOOTLOGO=1, TERMINFO=/system/etc/terminfo, EXTERNAL_STORAGE=/sdcard, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=11, PATH=/data/user/0/ru.meefik.linuxdeploy/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, TERM=linux, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/org.dirtyunicorns.utils.jar, ANDROID_PROPERTY_WORKSPACE=9,0, ANDROID_STORAGE=/storage]
10-27 13:00:50.423 12204-12335/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:211)
10-27 13:00:50.423 12204-12335/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:195)
10-27 13:00:50.423 12204-12335/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.exec(EnvUtils.java:304)
10-27 13:00:50.423 12204-12335/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.httpd(EnvUtils.java:580)
10-27 13:00:50.423 12204-12335/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.ExecService$1.run(ExecService.java:36)
10-27 13:00:50.423 12204-12335/ru.meefik.linuxdeploy W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-27 13:00:50.423 12204-12335/ru.meefik.linuxdeploy W/System.err: Caused by: java.io.IOException: No such file or directory
10-27 13:00:50.423 12204-12335/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(Native Method)
10-27 13:00:50.423 12204-12335/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:209)
10-27 13:00:50.423 12204-12335/ru.meefik.linuxdeploy W/System.err: 	... 5 more
10-27 13:00:50.428 12204-12334/ru.meefik.linuxdeploy W/System.err: java.io.IOException: Error running exec(). Command: [sh] Working Directory: /data/user/0/ru.meefik.linuxdeploy/env Environment: [ANDROID_ROOT=/system, LD_PRELOAD=libsigchain.so, ANDROID_BOOTLOGO=1, TERMINFO=/system/etc/terminfo, EXTERNAL_STORAGE=/sdcard, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=11, PATH=/data/user/0/ru.meefik.linuxdeploy/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, TERM=linux, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/org.dirtyunicorns.utils.jar, ANDROID_PROPERTY_WORKSPACE=9,0, ANDROID_STORAGE=/storage]
10-27 13:00:50.428 12204-12334/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:211)
10-27 13:00:50.428 12204-12334/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:195)
10-27 13:00:50.428 12204-12334/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.exec(EnvUtils.java:304)
10-27 13:00:50.428 12204-12334/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.telnetd(EnvUtils.java:550)
10-27 13:00:50.428 12204-12334/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.ExecService$1.run(ExecService.java:33)
10-27 13:00:50.429 12204-12334/ru.meefik.linuxdeploy W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-27 13:00:50.429 12204-12334/ru.meefik.linuxdeploy W/System.err: Caused by: java.io.IOException: No such file or directory
10-27 13:00:50.429 12204-12334/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(Native Method)
10-27 13:00:50.429 12204-12334/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:209)
10-27 13:00:50.429 12204-12334/ru.meefik.linuxdeploy W/System.err: 	... 5 more
10-27 13:00:50.510 12204-12204/ru.meefik.linuxdeploy I/Choreographer: Skipped 56 frames!  The application may be doing too much work on its main thread.
10-27 13:00:50.987 12204-12259/ru.meefik.linuxdeploy W/System.err: java.io.FileNotFoundException: env
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:313)
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:287)
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.extractFile(EnvUtils.java:54)
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.extractDir(EnvUtils.java:88)
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.updateEnv(EnvUtils.java:361)
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.UpdateEnvTask.doInBackground(UpdateEnvTask.java:26)
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.UpdateEnvTask.doInBackground(UpdateEnvTask.java:8)
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-27 13:00:51.020 12204-12259/ru.meefik.linuxdeploy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-27 13:00:51.021 12204-12259/ru.meefik.linuxdeploy W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-27 13:00:51.142 12204-12204/ru.meefik.linuxdeploy I/Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
10-27 13:00:51.472 12204-12256/ru.meefik.linuxdeploy V/RenderScript: 0xb83b8580 Launching thread(s), CPUs 4
10-27 13:00:59.688 12204-12212/ru.meefik.linuxdeploy W/art: Suspending all threads took: 313.349ms
10-27 13:00:59.889 12204-12212/ru.meefik.linuxdeploy W/art: Suspending all threads took: 12.565ms
10-27 13:01:00.315 12204-12204/ru.meefik.linuxdeploy I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
10-27 13:01:00.518 12204-12858/ru.meefik.linuxdeploy W/System.err: java.io.IOException: Error running exec(). Command: [sh] Working Directory: /data/user/0/ru.meefik.linuxdeploy/env Environment: [ANDROID_ROOT=/system, LD_PRELOAD=libsigchain.so, ANDROID_BOOTLOGO=1, TERMINFO=/system/etc/terminfo, EXTERNAL_STORAGE=/sdcard, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=11, PATH=/data/user/0/ru.meefik.linuxdeploy/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, TERM=linux, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/org.dirtyunicorns.utils.jar, ANDROID_PROPERTY_WORKSPACE=9,0, ANDROID_STORAGE=/storage]
10-27 13:01:00.535 12204-12859/ru.meefik.linuxdeploy W/System.err: java.io.IOException: Error running exec(). Command: [sh] Working Directory: /data/user/0/ru.meefik.linuxdeploy/env Environment: [ANDROID_ROOT=/system, LD_PRELOAD=libsigchain.so, ANDROID_BOOTLOGO=1, TERMINFO=/system/etc/terminfo, EXTERNAL_STORAGE=/sdcard, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=11, PATH=/data/user/0/ru.meefik.linuxdeploy/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, TERM=linux, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/org.dirtyunicorns.utils.jar, ANDROID_PROPERTY_WORKSPACE=9,0, ANDROID_STORAGE=/storage]
10-27 13:01:00.549 12204-12859/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:211)
10-27 13:01:00.549 12204-12859/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:195)
10-27 13:01:00.549 12204-12859/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.exec(EnvUtils.java:304)
10-27 13:01:00.549 12204-12859/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.httpd(EnvUtils.java:580)
10-27 13:01:00.549 12204-12859/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.ExecService$1.run(ExecService.java:36)
10-27 13:01:00.549 12204-12859/ru.meefik.linuxdeploy W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-27 13:01:00.549 12204-12859/ru.meefik.linuxdeploy W/System.err: Caused by: java.io.IOException: No such file or directory
10-27 13:01:00.549 12204-12859/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(Native Method)
10-27 13:01:00.549 12204-12859/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:209)
10-27 13:01:00.550 12204-12858/ru.meefik.linuxdeploy W/System.err: 	... 	at java.lang.ProcessManager.exec(ProcessManager.java:211)
10-27 13:01:00.550 12204-12858/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:195)
10-27 13:01:00.550 12204-12858/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.exec(EnvUtils.java:304)
10-27 13:01:00.550 12204-12858/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.telnetd(EnvUtils.java:550)
10-27 13:01:00.550 12204-12858/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.ExecService$1.run(ExecService.java:33)
10-27 13:01:00.550 12204-12858/ru.meefik.linuxdeploy W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-27 13:01:00.550 12204-12858/ru.meefik.linuxdeploy W/System.err: Caused by: java.io.IOException: No such file or directory
10-27 13:01:00.550 12204-12858/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(Native Method)
10-27 13:01:00.550 12204-12858/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:209)
10-27 13:01:00.550 12204-12858/ru.meefik.linuxdeploy W/System.err: 	... 5 more
10-27 13:01:00.551 12204-12859/ru.meefik.linuxdeploy W/System.err: 5 more
10-27 13:01:01.486 12204-12851/ru.meefik.linuxdeploy W/System.err: java.io.FileNotFoundException: env
10-27 13:01:01.511 12204-12851/ru.meefik.linuxdeploy W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
10-27 13:01:01.511 12204-12851/ru.meefik.linuxdeploy W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:313)
10-27 13:01:01.511 12204-12851/ru.meefik.linuxdeploy W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:287)
10-27 13:01:01.511 12204-12851/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.extractFile(EnvUtils.java:54)
10-27 13:01:01.511 12204-12851/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.extractDir(EnvUtils.java:88)
10-27 13:01:01.511 12204-12851/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.updateEnv(EnvUtils.java:361)
10-27 13:01:01.511 12204-12851/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.UpdateEnvTask.doInBackground(UpdateEnvTask.java:26)
10-27 13:01:01.511 12204-12851/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.UpdateEnvTask.doInBackground(UpdateEnvTask.java:8)
10-27 13:01:01.511 12204-12851/ru.meefik.linuxdeploy W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-27 13:01:01.511 12204-12851/ru.meefik.linuxdeploy W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-27 13:01:01.511 12204-12851/ru.meefik.linuxdeploy W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-27 13:01:01.512 12204-12851/ru.meefik.linuxdeploy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-27 13:01:01.512 12204-12851/ru.meefik.linuxdeploy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-27 13:01:01.512 12204-12851/ru.meefik.linuxdeploy W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-27 13:01:19.371 12204-13613/ru.meefik.linuxdeploy W/System.err: java.io.IOException: Error running exec(). Command: [sh] Working Directory: /data/user/0/ru.meefik.linuxdeploy/env Environment: [ANDROID_ROOT=/system, LD_PRELOAD=libsigchain.so, ANDROID_BOOTLOGO=1, TERMINFO=/system/etc/terminfo, EXTERNAL_STORAGE=/sdcard, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=11, PATH=/data/user/0/ru.meefik.linuxdeploy/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, TERM=linux, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/org.dirtyunicorns.utils.jar, ANDROID_PROPERTY_WORKSPACE=9,0, ANDROID_STORAGE=/storage]
10-27 13:01:19.395 12204-13613/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:211)
10-27 13:01:19.395 12204-13613/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:195)
10-27 13:01:19.395 12204-13613/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.exec(EnvUtils.java:304)
10-27 13:01:19.395 12204-13613/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.telnetd(EnvUtils.java:550)
10-27 13:01:19.395 12204-13613/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.ExecService$1.run(ExecService.java:33)
10-27 13:01:19.395 12204-13613/ru.meefik.linuxdeploy W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-27 13:01:19.395 12204-13613/ru.meefik.linuxdeploy W/System.err: Caused by: java.io.IOException: No such file or directory
10-27 13:01:19.395 12204-13613/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(Native Method)
10-27 13:01:19.395 12204-13613/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:209)
10-27 13:01:19.395 12204-13613/ru.meefik.linuxdeploy W/System.err: 	... 5 more
10-27 13:01:19.401 12204-13614/ru.meefik.linuxdeploy W/System.err: java.io.IOException: Error running exec(). Command: [sh] Working Directory: /data/user/0/ru.meefik.linuxdeploy/env Environment: [ANDROID_ROOT=/system, LD_PRELOAD=libsigchain.so, ANDROID_BOOTLOGO=1, TERMINFO=/system/etc/terminfo, EXTERNAL_STORAGE=/sdcard, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=11, PATH=/data/user/0/ru.meefik.linuxdeploy/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, TERM=linux, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/org.dirtyunicorns.utils.jar, ANDROID_PROPERTY_WORKSPACE=9,0, ANDROID_STORAGE=/storage]
10-27 13:01:19.401 12204-13614/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:211)
10-27 13:01:19.402 12204-13614/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:195)
10-27 13:01:19.402 12204-13614/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.exec(EnvUtils.java:304)
10-27 13:01:19.402 12204-13614/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.httpd(EnvUtils.java:580)
10-27 13:01:19.402 12204-13614/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.ExecService$1.run(ExecService.java:36)
10-27 13:01:19.402 12204-13614/ru.meefik.linuxdeploy W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-27 13:01:19.402 12204-13614/ru.meefik.linuxdeploy W/System.err: Caused by: java.io.IOException: No such file or directory
10-27 13:01:19.402 12204-13614/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(Native Method)
10-27 13:01:19.402 12204-13614/ru.meefik.linuxdeploy W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:209)
10-27 13:01:19.402 12204-13614/ru.meefik.linuxdeploy W/System.err: 	... 5 more
10-27 13:01:19.432 12204-12212/ru.meefik.linuxdeploy W/art: Suspending all threads took: 6.341ms
10-27 13:01:20.042 12204-13600/ru.meefik.linuxdeploy W/System.err: java.io.FileNotFoundException: env
10-27 13:01:20.048 12204-13600/ru.meefik.linuxdeploy W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:313)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:287)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.extractFile(EnvUtils.java:54)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.extractDir(EnvUtils.java:88)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.updateEnv(EnvUtils.java:361)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.UpdateEnvTask.doInBackground(UpdateEnvTask.java:26)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at ru.meefik.linuxdeploy.UpdateEnvTask.doInBackground(UpdateEnvTask.java:8)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-27 13:01:20.049 12204-13600/ru.meefik.linuxdeploy W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

Seems like it's trying to run a shell script called "env" but when I manually navigate to the directory (/data/user/0/ru.meefik.linuxdeploy/ using ESExplorer) I cannot see any env file nor folder.

Is it some kind of bug or is it just me compiling it wrongly? 

Greetings.

**Comment by rkkoszewski** [comment]
I seem to have the same issue when I compile Alpha 2.0.0.
Seems like all calls to System.exec() are blocked. This doesn't happen when I install LinuxDeploy from Google Play or from Release.
Are there any special flags used to compile LinuxDeploy? (I'm using Android Studio)

**Comment by meefik** [comment]
Apparently the directory /data/user/0/ru.meefik.linuxdeploy/env not included in the project and not unpacked in Android. You must manually copy (or symlinked) [branch cli](https://github.com/meefik/linuxdeploy/tree/cli) to directory /app/src/main/assets of the project.

**Comment by rkkoszewski** [comment]
Thanks! That was it!

**Comment by lmorda** [comment]
Yes thanks this also worked for me.

When I build master and run the app:
java.io.IOException: Cannot run program "sh" (in directory "/data/user/0/ru.meefik.linuxdeploy/env"): error=2, No such file or directory

But now I moved branch cli into a folder "env" and placed that folder into my /app/src/main/assets of the project.  I am now able to update environment.
